### ISSUE TITLE
Failed Play Song

### ISSUE THREAD

**Issue by REMOOO** [Tomato6966/light-music-bot#2]
the bot not play song from soundcloud or soptify

**Comment by jakehe1226** [comment]
If you have a look at the code, it only accepts and plays YouTube links. So no SoundCloud or Spotify at the moment.

**Comment by Tomato6966** [comment]
it does not use any open source scraper moduls. 
Spotify link support is enable able, same for deezer, but idk how to make a proper soundcloud scraper.
I might add those features during the yt tutorial series
